
GET http://localhost:8000/ok
###
GET http://localhost:8000/timeout
###
GET http://localhost:8000/vehicleData
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
###
GET http://localhost:8000/vehicleSpecificationsData
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYWl0aHdAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjAwOTExMzF9.qYJG6RnwtvJ_E1oeqgBXw2hEN7EwETZ53tIkF7tX5u0
###
GET http://localhost:8000/fleetManagementData
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
###
GET http://localhost:8000/customerSupportTicketsData
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
###
GET http://localhost:8000/bookings
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
######
GET http://localhost:8000/bookingsData
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
###
GET http://localhost:8000/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
###
GET http://localhost:8000/locationBranches
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
###
GET http://localhost:8000/locationBranches/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
###
GET http://localhost:8000/payments/2
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
###
GET http://localhost:8000/paymentsData
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
###
GET http://localhost:8000/vehicle/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
###
put http://localhost:8000/users/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c

{
    "full_name": "faith wanjiru",
    "email":"faithw@gmail.com",
    "contact_phone": "+254187324234",
     "address": "Nairobi, Kenya",
     "role":"user"
}
###
DELETE http://localhost:8000/users/10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
###
POST http://localhost:8000/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
Content-Type: application/json

{
   
    "full_name": "kevin wangari",
    "email":"kevinw@gmail.com",
    "contact_phone": "+254187324234",
     "address": "murang'a, Kenya",
     "role":"userAdminRoleAuth"
}
###
POST http://localhost:8000/vehicle
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
Content-Type: application/json

{

    "vehicleSpec_id": 1,
    "rental_rate": 20,
    "availability":"available"
}

###
POST http://localhost:8000/vehicleSpecifications
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
Content-Type: application/json

{
   
   "manufacturer":"toyota",
    "model":"Sienta",
   "year":2023,
   "fuel_type":"petrol",
   "engine_capacity":"21c",
   "transmission":"good",
   "seating_capacity":9,
    "color":"black",
    "features": "6 months used"
}
###
POST http://localhost:8000/bookings
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdXRoZWUuMTQ5NTJAc3R1ZGVudHMua3l1LmFjLmtlIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwMDkxNDA3fQ.Miqf83yk1ST_o3bJawO_3MOZcFTlQXLz3z7fek9xa5c
Content-Type: application/json

{
   "user_id": 2,
   "vehicle_id": 2,
   "location_id": 1,
   "booking_date": 2021-02-03,
   "return_date": 2021-02-05,
   "total_amount": 20000,
   "booking_status": "booked"
}

###
POST http://localhost:8000/register
Content-Type: application/json

{
     "user_id": 2,
     "email":"e@gmail.com",
    "password":"pass",
    "role":"user"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "e@gmail.com",
    "password":"pass"
}